In [169]:
import torch

In [170]:
p = torch.Tensor([0.5])
r = torch.bernoulli(input=p)

print(r)
print(r.shape)

tensor([1.])
torch.Size([1])


In [171]:
x = torch.rand((64, 16))
print(x)

tensor([[0.1954, 0.3021, 0.7284,  ..., 0.8377, 0.9948, 0.4682],
        [0.4862, 0.8821, 0.3231,  ..., 0.4625, 0.7741, 0.2495],
        [0.7443, 0.1966, 0.5096,  ..., 0.1827, 0.0737, 0.2609],
        ...,
        [0.2714, 0.2442, 0.3432,  ..., 0.0886, 0.8730, 0.5972],
        [0.5106, 0.0736, 0.8899,  ..., 0.9220, 0.8114, 0.7118],
        [0.9563, 0.4086, 0.9481,  ..., 0.3755, 0.4273, 0.6412]])


In [172]:
x = torch.rand((64, 16))
probs = torch.ones_like(x) * p
r = torch.bernoulli(probs)
print(r)
print(r.shape)

tensor([[1., 0., 1.,  ..., 0., 1., 0.],
        [1., 0., 1.,  ..., 1., 0., 0.],
        [1., 1., 1.,  ..., 1., 1., 0.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 0.],
        [1., 1., 0.,  ..., 0., 0., 0.],
        [1., 1., 0.,  ..., 0., 1., 1.]])
torch.Size([64, 16])


In [173]:
x_hat = x * r
print(x_hat)
print(x_hat.shape)

tensor([[0.9174, 0.0000, 0.4360,  ..., 0.0000, 0.2725, 0.0000],
        [0.6742, 0.0000, 0.4429,  ..., 0.6216, 0.0000, 0.0000],
        [0.3199, 0.6182, 0.6572,  ..., 0.9681, 0.8221, 0.0000],
        ...,
        [0.9149, 0.0789, 0.9458,  ..., 0.2666, 0.2809, 0.0000],
        [0.3710, 0.3810, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.4793, 0.8719, 0.0000,  ..., 0.0000, 0.4489, 0.6243]])
torch.Size([64, 16])


In [ ]:
x_hat = torch.mul(x, r) 
print(x_hat)
print(x_hat.shape)